# Generated by Django 3.0.5 on 2020-04-16 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_case', models.IntegerField()),
                ('new_lab', models.IntegerField()),
                ('total_case', models.IntegerField()),
                ('total_lab', models.IntegerField()),
                ('recovered', models.IntegerField()),
                ('deceased', models.IntegerField()),
            ],
        ),
    ]
